development:
  adapter: mysql2
  encoding: utf8
  database: todo_list_dev
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: todo_list_prod
  username: root
  password: 
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: todo_list_test
  username: root
  password: 
  host: localhost